**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [18]:
#Code here
a = np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [21]:
#Code here
a= int(input('a = '))
b= int(input('b = '))

def array_create(a,b):
    arr_ = np.random.random(a*b).reshape(a,b)
    return arr_

print(array_create(a,b))
print("Average = ",arr.mean())

a =  3
b =  4


[[0.94105292 0.91939364 0.5374036  0.40457993]
 [0.64942867 0.07528236 0.63995116 0.67955165]
 [0.6963847  0.28129841 0.17322305 0.75713102]]
Average =  0.5961297562279773


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [28]:
#Code here
a= int(input('a = '))
b= int(input('b = '))

def border_array(a,b):
    arr_ = np.ones(a*b,dtype=int).reshape(a,b)
    arr_[1:-1,1:-1]=0
    return arr_

border_array(a,b)

a =  4
b =  5


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [37]:
#Code here
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

#Code here- 
No Its not possible as rows and columns should be same foridentity matrix.

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [52]:
#Code here
a1 = np.zeros((5,5))
a1+=np.arange(5)
a1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [63]:
#code here
arr_ = np.random.randint(1,100,(10,2))
point = np.array([2,3])
np.sqrt(np.sum((arr_-point)**2, axis=1)).astype(int)

array([41, 24, 44, 69, 20, 70, 70, 18, 76, 54])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [68]:
#Code here
arr_ = np.zeros((6,7,8))
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [77]:
#Code here
a = input().strip().split()
np.array(a[::-1],dtype=float)

 1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [82]:
#Code here
a= np.array([1,2])
print("array = ",a)
print("eleents_count : ",a.size)

array =  [1 2]
eleents_count :  2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [106]:
#Code here
def softmax(arr):
    if type(arr)!=np.ndarray:
         raise TypeError("Requires Numpy Array")   
    elif arr.ndim>1:
        raise TypeError("Requires 1D Array only")
    else:
        s = np.sum(np.exp(arr))
        return np.exp(arr)/s
arr = np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318])
print(softmax(arr))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


In [107]:
arr= np.array([33.17344305,45.61961654,82.05405781,80.9647098,68.82830233,91.52064278])
print(softmax(arr))

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [117]:
#Coder here
def stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Input argument is not an array. Only Arrays are allowed")
        else:
            return np.vstack(args)

a = np.arange(10).reshape(2,-1)
print("a = ",a,a.shape)
b = np.random.random((2,5)).reshape(2,-1)
print("b = ",b, b.shape)
c = np.linspace(1,11,10).reshape(2,5)
print("c = ",c, c.shape)
stack(a,b,c)

a =  [[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
b =  [[0.07767907 0.25318565 0.32963491 0.43221188 0.94804185]
 [0.65653283 0.66878798 0.44883445 0.66896404 0.84752696]] (2, 5)
c =  [[ 1.          2.11111111  3.22222222  4.33333333  5.44444444]
 [ 6.55555556  7.66666667  8.77777778  9.88888889 11.        ]] (2, 5)


array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [ 0.07767907,  0.25318565,  0.32963491,  0.43221188,  0.94804185],
       [ 0.65653283,  0.66878798,  0.44883445,  0.66896404,  0.84752696],
       [ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444],
       [ 6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [121]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, 
                           "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    
    # Use arange() to generate all dates between start and end 
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [135]:
#code here
x = np.random.random((5,4))
x-x.mean(axis=1, keepdims=True)

array([[-0.24401813,  0.1603314 , -0.13390995,  0.21759668],
       [-0.02414681, -0.24860982,  0.25490698,  0.01784964],
       [-0.17738599,  0.50936941, -0.33777142,  0.005788  ],
       [ 0.35126704,  0.00999029, -0.40125994,  0.04000261],
       [-0.25859888,  0.24366247, -0.19779608,  0.2127325 ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [137]:
#Code here
arr= np.arange(9).reshape(3,3)
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [140]:
#Code here
arr= np.arange(10)
arr[arr%2 == 1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [142]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a]= b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [157]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
print(arr1[:,::2])

[[2954 7512 3732 1422 3803]
 [1462 3749 2337  515 9448]
 [6221 9997 9695 8980 9229]
 [3615 9199 1818 8493  977]
 [4349 8940 3548 6335 1458]
 [4770 5514 2683 5674 5880]
 [6173 8179 7265 4273 2391]
 [ 465 5408 2025  191 5923]]
[[2954 3732 3803]
 [1462 2337 9448]
 [6221 9695 9229]
 [3615 1818  977]
 [4349 3548 1458]
 [4770 2683 5880]
 [6173 7265 2391]
 [ 465 2025 5923]]


In [158]:
#Code here
arr_norm = (arr1 - arr1.min())/(arr1.max() - arr1.min())
arr_norm

array([[0.28176627, 0.74658372, 0.36110545, 0.12553539, 0.36834591],
       [0.12961452, 0.36283908, 0.2188456 , 0.033041  , 0.94401387],
       [0.61492963, 1.        , 0.96920253, 0.89628799, 0.9216806 ],
       [0.34917398, 0.91862125, 0.16591883, 0.84662452, 0.08015501],
       [0.42402611, 0.89220885, 0.34234142, 0.62655517, 0.12920661],
       [0.466959  , 0.54283092, 0.25413012, 0.55914746, 0.58015501],
       [0.61003467, 0.8146033 , 0.72139506, 0.41627575, 0.22435244],
       [0.02794208, 0.53202121, 0.18702835, 0.        , 0.58454008]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [159]:
#Code here
def max_val(arr, n):
    if n>len(arr):
        raise IndexError("value is out of limit")
    arr.sort()
    return arr[-n]
max_val(np.array([12,34,40,7,1,0]),3)

12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [166]:
#code here
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])